---
layout: post
title: "Spatial Intro 09: R Packages for Spatial-temporal Data -- Setting Up Your Working Environment"
date:   2015-10-21
authors: []
contributors: [ ]
dateCreated: 2015-10-23
lastModified: `r format(Sys.time(), "%Y-%m-%d")`
packagesLibraries: [ ]
category: [self-paced-tutorial]
tags: [R, spatial-data-gis]
mainTag: spatial-data-management-series
workshopSeries: [spatial-data-management-series]
description: "This lesson covers the key packages that support working with
spatial data in R."
code1: /R/dc-spatio-temporal-intro/09-set-r-work-environment.R
image:
  feature: NEONCarpentryHeader_2.png
  credit: A collaboration between the National Ecological Observatory Network (NEON) and Data Carpentry
  creditlink:
permalink: R/spatio-temporal-R-packages
comments: true
---

{% include _toc.html %}

## About
Add description.

**R Skill Level:** Intermediate - you've got the basics of `R` down.

<div id="objectives" markdown="1">

# Goals / Objectives

After completing this activity, you will:

*
* Understand that different spatial data types & associated file types require
different tools to work with them.

## Things You’ll Need To Complete This Lesson
To complete this lesson you will need the most current version of R, and
preferably, RStudio loaded on your computer.

### Install R Packages

* **NAME:** `install.packages("NAME")`

* [More on Packages in R - Adapted from Software Carpentry.]({{site.baseurl}/R/Packages-In-R/)

### Download Data
EDIT AS NEEDED

<h3> <a href="https://ndownloader.figshare.com/files/3701578"> NEON Teaching Data Subset: Airborne Remote Sensing Data </a></h3>

The LiDAR and imagery data used to create this raster teaching data subset 
were collected over the 
<a href="https://www.neonscience.org/" target="_blank"> National Ecological Observatory Network's</a> 
<a href="https://www.neonscience.org/field-sites/field-sites-map/HARV" target="_blank" >Harvard Forest</a>
and 
<a href="https://www.neonscience.org/field-sites/field-sites-map/SJER" target="_blank" >San Joaquin Experimental Range</a>
field sites and processed at NEON headquarters. 
The entire dataset can be accessed by request from the 
<a href="http://data.neonscience.org" target="_blank"> NEON Data Portal</a>.

<a href="https://ndownloader.figshare.com/files/3701578" class="link--button link--arrow"> Download Dataset</a>





****

**Set Working Directory:** This lesson assumes that you have set your working 
directory to the location of the downloaded and unzipped data subsets. 

<a href="https://www.neonscience.org/set-working-directory-r" target="_blank"> An overview
of setting the working directory in R can be found here.</a>

**R Script & Challenge Code:** NEON data lessons often contain challenges that reinforce 
learned skills. If available, the code for challenge solutions is found in the
downloadable R script of the entire lesson, available in the footer of each lesson page.


**Spatial-Temporal Data & Data Management Lesson Series:** This lesson is part
of a lesson series introducing
[spatial data and data management in `R` ](https://www.neonscience.org/tutorial/URL).
It is also part of a larger
[spatio-temporal Data Carpentry Workshop ](https://www.neonscience.org/workshops/spatio-temporal-workshop)
that includes working with  
[raster data in `R` ](https://www.neonscience.org/tutorial/spatial-raster-series),
[vector data in `R` ](https://www.neonscience.org/tutorial/spatial-vector-series)
and  
[tabular time series in `R` ](https://www.neonscience.org/tutorial/tabular-time-series).

****

### Additional Resources

* <a href="http://cran.r-project.org/web/packages/raster/raster.pdf" target="_blank">
Read more about the `raster` package in `R`.</a>
* <a href="http://neondataskills.org/R/Raster-Data-In-R/" target="_blank" >
NEON Data Skills: Raster Data in R - The Basics</a>
* <a href="http://neondataskills.org/R/Image-Raster-Data-In-R/" target="_blank" >
NEON Data Skills: Image Raster Data in R - An Intro</a>

</div>

## raster

## rgdal

## rastervis - time series plotting

## Set up working directory - <<link to working directory page??> 
