---
syncID: c91c9a163403426eba4f95c2e823e4a4
title: "Test reticulate tabs in iframe"
description: Test for tabbed tutorials with R and Python code. Do not publish this tutorial.
dateCreated: '2024-06-25'
dataProducts: 
authors: Claire K. Lunch
contributors: 
estimatedTime: 0 hours
packagesLibraries: neonUtilities, neonutilities
topics: data-management, rep-sci
languageTool: R, Python
code1: https://raw.githubusercontent.com/NEONScience/NEON-Data-Skills/main/tutorials/Other/Concept-intros/test_tabs_iframe/test_code_tabs_iframe.R
tutorialSeries:
urlTitle: test-code-tabs-iframe
---

```{r setup, echo=FALSE}

library(htmltools)
library(httr)
res <- GET("https://api.github.com/repos/cklunch/NEON-Data-Skills/contents/tutorials-in-development/Other/test_code_tabs.html")
r2 <- content(res)
download.file(r2$download_url, destfile=paste(getwd(), "/tut_html.html", sep=""), mode="wb", quiet=T)

```


```{r html, echo=FALSE, warning=FALSE, message=FALSE}

htmltools::tags$iframe(src = base64enc::dataURI(file=paste(getwd(), "/tut_html.html", sep=""), 
                                                mime="text/html; charset=UTF-8"), width="100%", 
                       height=1600, frameborder="0", seamless="seamless")

```

``` {r cleanup, echo=FALSE}

unlink(paste(getwd(), "/tut_html.html", sep=""))

```
