---
syncID: 
title: "NEON-CUAHSI Data Skills Demo: Exploring the Water Cycle at Co-Located Terrestrial-Aquatic Sites"	
description: Hands-on data skills demo on how to download, explore, manipulate, and visualize NEON hydrology data at co-located terrestrial and aquatic sites. Presented in collaboration with the CUAHSI cyberseminar series on April 1, 2026.	
dateCreated: 2026-03-19
authors: Zachary L. Nickerson
contributors: Nicolas M. Harrison
estimatedTime: 1.25 hours
packagesLibraries: neonUtilities, tidyverse, geosphere, plotly # Update
topics: data-download, data-manipulation, data-visualization
subtopics: hydrology, water cycle, precipitation, groundwater, discharge
languagesTool: R, API, Python
dataProduct: DP1.00045.001, DP1.20100.001, DP1.20206.001, DP4.00130.001, DP4.00131.001, DP4.00200.001
code1:  # Update
tutorialSeries: 
urlTitle: water-cycle-colocated-sites
editor_options: 
  markdown: 
    wrap: 72
---


```{r setup, echo=FALSE}

library(htmltools)

```


```{r html, echo=FALSE, warning=FALSE, message=FALSE}

htmltools::includeHTML("https://raw.githubusercontent.com/NEONScience/NEON-Data-Skills/refs/heads/main/tutorials/R/AIS-data/NEON-hydrology-tutorial/neon-hydro-colocated-water-cycle-content.html")

```
