---
syncID: 99d22b526c1a4a88847259a4d05b46af
title: "Using an API Token when Accessing NEON Data with neonUtilities"
description: "Get an API token tied to your NEON user account, and use it for faster download speeds when accessing NEON data via the neonUtilities package."
dateCreated: 2020-05-04
authors: [Claire K. Lunch]
contributors: [Maxwell Burner]
estimatedTime: 20 minutes
packagesLibraries: neonUtilities
topics: data-management, rep-sci
languageTool: R
dataProduct: DP1.10026.001, DP3.30015.001
code1: https://raw.githubusercontent.com/NEONScience/NEON-Data-Skills/main/tutorials/R/NEON-general/neon-code-packages/NEON-API-Token/neon-api-tokens-tutorial/neon-api-tokens-tutorial.R
tutorialSeries:
urlTitle: neon-api-tokens-tutorial

---

```{r setup, echo=FALSE}

library(htmltools)

```


```{r html, echo=FALSE, warning=FALSE, message=FALSE}

htmltools::includeHTML("https://raw.githubusercontent.com/NEONScience/NEON-Data-Skills/refs/heads/main/tutorials/R/NEON-general/neon-code-packages/NEON-API-Token/neon-api-tokens-tutorial/neon-api-tokens-content.html")

```

