---
title: "r-TimeSeries-HDF5"
author: "Leah A Wasser"
date: "Wednesday, May 20, 2015"
output: html_document
---

```{r}
#source("http://bioconductor.org/biocLite.R")
#biocLite("rhdf5")


library("rhdf5")
library("ggplot2")
```

Let's begin by opening up a H5 file

```{r, echo=FALSE}

f <- 'NEON_TowerDataD3_D10.hdf5'
h5ls(f)

# HDF5 allows us to quickly extract parts of a dataset or even groups.
# extract temperature data from one site (Ordway Swisher, Florida) and plot it

temp <- h5read(f,"/Domain_03/OSBS/min_1/boom_1/temperature")
#view the header and the first 6 rows of the dataset
head(temp)
#generate a quick plot, type - l for line 
plot(temp$mean,type='l')

#let's fix up the plot above a bit. We can first add dates to the x axis. 
#in order to list dates, we need to specify the format that the date field is in.
temp$date <- as.POSIXct(temp$date ,format = "%Y-%m-%d %H:%M:%S", tz = "EST")

ordwayPlot <- qplot (date,mean,data=temp,geom="line", title="ordwayData",
                 main="Mean Temperature - Ordway Swisher", xlab="Date", 
                 ylab="Mean Temperature (Degrees C)")

#let's check out the plot
ordwayPlot

####################
#more info on customizing plots
#http://www.statmethods.net/advgraphs/ggplot2.html
######################
```

```{r}

## View the groups and datasets in our file, 
#we will grab the nested structure, 5 'levels' down
#5 levels gets us to the temperature dataset
fiu_struct <- h5ls(f,recursive=5)

## have a look at the structure.
fiu_struct

#now we can use this object to pull group paths from our file!
fiu_struct[3,1]

## Let's view the metadata for the OSBS group
OSBS  <- h5readAttributes(f,fiu_struct[3,1])
#view the attributes
OSBS

#grab the lat and long from the data
#note we might want to format the lat and long differently 
#this format is more difficult to extract from R!
OSBS$LatLon

```

#Challenge

1. How would you rewrite the metadata for each site to make it more user friendly? Discuss with your neighbor. Map out an H5 file that might contain more useful information.


```{r}

#r compare temperature data for different booms at the Ordway Swisher site.
library(dplyr)
library(ggplot2)

#we could do the next part in a few ways

# Set the path string
#s <- fiu_struct[4,1]

#use dplyr to subset data by dataset name (temperature)
# and site / 1 minute average
newStruct <- fiu_struct %>% filter(grepl("temperature",name),
                                   grepl("OSBS/min_1",group))

#create final paths
paths <- paste(newStruct$group,newStruct$name,sep="/")

#create a new, empty data.frame
ord_temp <- data.frame()

#loop through each temp dataset and add to data.frame
for(i in paths){
  datasetName <- i
  print(datasetName) 
  #read in each dataset in the H5 list
  dat <- h5read(f,datasetName)
  # add boom name to data.frame
  print(strsplit(i,"/")[[1]][5]) 
  dat$boom <- strsplit(i,"/")[[1]][5]
  ord_temp <- rbind(ord_temp,dat)
}


#fix the dates
ord_temp$date <- as.POSIXct(ord_temp$date,format = "%Y-%m-%d %H:%M:%S", tz = "EST")

#plot the data
ggplot(ord_temp,aes(x=date,y=mean,group=boom,colour=boom))+
  geom_path()+
  ylab("Mean temperature") + xlab("Date")+
  theme_bw()+
  ggtitle("3 Days of temperature data at Ordway Swisher")+
  scale_x_datetime( breaks=pretty_breaks(n=4))


```

Create a summary plot comparing temperature at two sites.

```{r}
#grab just the paths to temperature data, 30 minute average
pathStrux <- fiu_struct %>% filter(grepl("temperature",name), 
                                   grepl("min_30",group)) 
#create final paths
paths <- paste(pathStrux$group,pathStrux$name,sep="/")

#create empty dataframe
temp_30 <- data.frame()

for(i in paths){
  #create columns for boom name and site name
  boom <-  strsplit(i,"/")[[1]][5]
  site <- strsplit(i,"/")[[1]][3]
  dat <- h5read(f,i)
  dat$boom <- boom
  dat$site <- site
 temp_30 <- rbind(temp_30,dat)
}

#Assign the date field to a "date" format in R
temp_30$date <- as.POSIXct(temp_30$date,format = "%Y-%m-%d %H:%M:%S")

# generate a mean temperature for every date across booms
temp30_sum <- temp_30 %>% group_by(date,site) %>% summarise(mean = mean(mean))

#Create plot!
ggplot(temp30_sum,aes(x=date,y=mean,group=site,colour=site)) + 
  geom_path()+ylab("Mean temperature, 30 Minute Average") + 
  xlab("Date")+
  theme_bw()+
  ggtitle("Comparison of Ordway-Swisher Biological Station (FL) vs North Sterling (CO)") +
  scale_x_datetime( breaks=pretty_breaks(n=4))

```

