---
layout: post
title: "Lesson Title Goes here"
date:   2015-1-26 20:49:52
authors: "FirstName LastName, FirstName LastName"
dateCreated:  2014-11-26 20:49:52
lastModified: 2015-07-23 14:28:52
category: time-series-workshop
tags: [module-1]
mainTag: GIS-Spatial-Data
description: "This post explains the fundamental principles, functions and metadata that you need to work with raster data in R."
code1: 
image:
  feature: lidar_GrandMesa.png
  credit: LiDAR data collected over Grand Mesa, Colorado - National Ecological Observatory Network (NEON)
  creditlink: http://www.neoninc.org
permalink: /R/Raster-Data-In-R/
code1: /R/2015-07-22-Introduction-to-Raster-Data-In-R.R
comments: true

---

<section id="table-of-contents" class="toc">
  <header>
    <h3>Contents</h3>
  </header>
<div id="drawer" markdown="1">
*  Auto generated table of contents
{:toc}
</div>
</section><!-- /#table-of-contents -->

##About
This section introduces the Remote Sensing Module and gives some links to important background information that may be useful. For this module you should already be reasonably familiar with raster data, vector data, time series data, and creating maps/plots in R. If you attened the data carpentry workshop on geospatial data, you're in good shape. If not, or if you need to review, below are links to the lessons and activites from that workshop. 

**R Skill Level:** Intermediate - you've got the basics of `R` down.

<div id="objectives">

<h3>Goals / Objectives</h3>
After completing the Remote Sensing Module, you will know:
<ol>
<li>The basics of remote sensing in visible, multispectral, and hyperspectral and their relative benefits</li>
<li>How to work with remote sensing data in R</li>
<li>How to work with LiDAR data in R</li>
</ol>

<h3>Things You'll Need To Complete This Lesson</h3>

<h3>R Libraries to Install:</h3>
<ul>
<li><strong>raster:</strong> <code> install.packages("raster")</code></li>
<li><strong>rgdal:</strong> <code> install.packages("rgdal")</code></li>

</ul>
<h4>Tools To Install</h4>

Please be sure you have the most current version of `R` and preferably
R studio to write your code.


<h4>Data to Download</h4>

Download the raster and *in situ* collected vegetation structure data:
<ul>
<li><a href="http://neonhighered.org/Data/LidarActivity/CHM_InSitu_Data.zip" class="btn btn-success"> DOWNLOAD Sample NEON LiDAR data in Raster Format & Vegetation Sampling Data</a></li>
<li><a href="{{ site.baseurl }}/data/rasterLayers_tif.zip" class="btn btn-success"> DOWNLOAD NEON imagery data (tiff format) California Domain 17 (D17)</a></li>
</ul>

<p>The LiDAR and imagery data used to create the rasters in this dataset were 
collected over the San Joaquin field site located in California (NEON Domain 17) 
and processed at <a href="http://www.neoninc.org" target="_blank" >NEON </a> 
headquarters. The entire dataset can be accessed by request from the NEON website.</p>  

<h4>Recommended Pre-Lesson Reading</h4>
<ul>
<li>
<a href="{{ site.baseurl }}/GIS-Spatial-Data/Working-With-Rasters/" target="_blank">
The Relationship Between Raster Resolution, Spatial extent & Number of Pixels - in R</a>
</li>
<li>
<a href="http://cran.r-project.org/web/packages/raster/raster.pdf" target="_blank">
Read more about the `raster` package in R.</a>
</li>
</ul>
</div>

##Basics of Working with Spatial Data

<a href="https://github.com/data-lessons/NEON-R-Spatial-Data-Intro"> NEON + Data Carpentry lessons on working with spatial data.</a>

##Raster Data

<a href="https://github.com/data-lessons/NEON-R-Spatial-Raster"> NEON + Data Carpentry Lessons on rasters here.</a>

##Vector Data

<a href="https://github.com/data-lessons/NEON-R-Spatial-Raster"> NEON + Data Carpentry lessons on vectors here.</a>

##Time Series Data

<a href="https://github.com/data-lessons/NEON-R-Tabular-Time-Series"> NEON + Data Carpentry lessons on time series spatial data.</a>

##Creating Maps/Plots

<a href="https://github.com/data-lessons/NEON-R-Make-Pretty-Maps-Plots"> NEON + Data Carpentry lessons on creating maps and plots with spatial data in R.</a>

